FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /Zoo.Web
COPY "Zoo.Web.csproj" .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app


FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Zoo.Web.dll"]

